# name: MasterDeploy
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: Create Release Folder
#       run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
#     - name: Switch to Release Folder
#       run: |
#         cd release
#         ls -la
#     - name: Bump version and push tag
#       uses: satingaux/episource@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.TOKEN }}
#         REPO_OWNER: satingaux


on:
  push:
#     # Sequence of patterns matched against refs/tags
#     tags:
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
