

name: Create Release

on:
  push:
    branches: [ main ]
#   push:
#     branches: [ master ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master or main
        uses: actions/checkout@v2 # actions/checkout@main
      - name: Read current_version from version.ini file
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.ini
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}  
          current_version: ${{ steps.package.outputs.content }}
          last_version:  $GITHUB_REF  #0.0 default if statement
      - name: current_version from version.ini file
        run: echo " $env.RELEASE_VERSION & $current_version & $last_version & $GITHUB_REF & ${{ steps.package.outputs.content }}"
        
        
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release2
            - First Change
            - Second Change
          draft: false
          prerelease: false
