name: Create Release
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master or main
        uses: actions/checkout@v2 # actions/checkout@main

      - name: Read current_version from version.ini file
        id: version_package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.ini
        env:
          current_version: ${{ steps.version_package.outputs.content }}
          last_version:  ${{ steps.vars.outputs.tag }}  #0.0 default if statement
      - name: current_version from version.ini file
        run: |
          echo "${{ steps.version_package.outputs.content }}"
          echo "$GITHUB_REF"
          
#       - name: is last version exists
#         id: is_last_version_null
#         if: ${{ steps.version_package.outputs.content }} == null
#         run: $last_version = 0.0
#         continue-on-error: true

#       - name: compare new and old version
#         id: compare_versions
#         if: $current_version == $last_version
#         run: |
#           echo "Current Version is equal to last version, So no version update and no release as well"
#           exit 1

        
        
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 1.1
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release2
            - First Change
            - Second Change
          draft: false
          prerelease: false
