

name: Create Release

on:
  push:
    branches: [ main ]
#   push:
#     branches: [ master ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2 # actions/checkout@main
      - name: Read version.ini
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.ini
      - name: Echo version.ini
        run: echo ${{ steps.package.outputs.content }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release2
            - First Change
            - Second Change
          draft: false
          prerelease: false
