name: py
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: checkout repo content
       uses: actions/checkout@v2 # checkout the repository content to github runner.
     - name: setup python
       uses: actions/setup-python@v2
       with:
         python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
         architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
#      - name: execute py script # run the run.py to get the latest data
#        id: isCurrentVersionCorrect
#        run: |
#          python -m pip install --upgrade pip
#          pip install PyGithub
#          python compareVersions.py v2.21 v2.22 ${{ secrets.GITHUB_TOKEN }}
         
     - name: isCurrentVersionCorrect
       id: step1
       run: |
          output=$(python compareVersions.py v2.21 v2.22)
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$output"
          
        
     - name: Print changelog
       run: echo "${{ steps.step1.outputs.changelog }}"
       env:
        key: ${{ secrets.GITHUB_TOKEN }} # if run.py requires passwords..etc, set it as secrets
